# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-512afb25-4105-45fd-aced-432b80d606ac";
      fsType = "btrfs";
      options = [ "subvol=nixos-root" ];
    };

  boot.initrd.luks.devices."luks-512afb25-4105-45fd-aced-432b80d606ac".device = "/dev/disk/by-uuid/512afb25-4105-45fd-aced-432b80d606ac";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-512afb25-4105-45fd-aced-432b80d606ac";
      fsType = "btrfs";
      options = [ "subvol=nixos-home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-512afb25-4105-45fd-aced-432b80d606ac";
      fsType = "btrfs";
      options = [ "subvol=nixos-nix" ];
    };

  fileSystems."/var/steam-library" =
    { device = "/dev/mapper/luks-512afb25-4105-45fd-aced-432b80d606ac";
      fsType = "btrfs";
      options = [ "subvol=steam-library" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E1E7-1988";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
