# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-d72e126a-74da-4294-8e5c-accc168774b5";
      fsType = "btrfs";
      options = [ "subvol=nix-root" ];
    };

  boot.initrd.luks.devices."luks-d72e126a-74da-4294-8e5c-accc168774b5".device = "/dev/disk/by-uuid/d72e126a-74da-4294-8e5c-accc168774b5";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-d72e126a-74da-4294-8e5c-accc168774b5";
      fsType = "btrfs";
      options = [ "subvol=nix-home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/31C1-2B9B";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
